#!/usr/bin/with-contenv bash

echo "Waiting for litestream to start, sleeping for 5 seconds"
sleep 5 # Give litestream a chance to start

# Prepare the database
echo "Initializing database"
python3 /app/run_init_db.py
if [ $? -eq 0 ]; then
   echo "Database initialization succeeded"
else
   echo "Database initialization failed"
   exit 1
fi

# Set up log directory if it does not already exist
echo "Creating /var/log directory if it does not already exist"
mkdir -p /var/log

# Run the website
echo "Starting gunicorn with 1 workers"
exec gunicorn run-website:app \
    --chdir /app --workers 1 --bind 0.0.0.0:9205 \
    --access-logfile /var/log/gunicorn.access.log \
    --error-logfile /var/log/gunicorn.error.log \
    --log-file /var/log/gunicorn.log \
    --capture-output \
    --log-level INFO 